### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by jamestutsplus** [genedelisa/Swift2MIDI#1]
Hello I am using the latest Beta of Xcode  there is an error in the code.

let packet:MIDIPacket = packets.packet.0  Value of type 'MIDIPacket' has no member '0'

Thanks

**Comment by jamestutsplus** [comment]
Well actually quite a few more in MidiManager.swift, I don't have a clue... Thanks for the code.

**Comment by genedelisa** [comment]
Yes, they have changed how those tuples are used. In many places such as the MIDIThru classes, they are replacing the tuples with arrays - which is a good idea I think.

I'm in the middle of getting a project out the door right now, but I'll update this project as soon as I can.

**Comment by genedelisa** [comment]
updated to Xcode 7 beta 6 syntax
