### ISSUE TITLE
MIDIDestinationCreateWithBlock never called

### ISSUE THREAD

**Issue by ghost** [genedelisa/Swift2MIDI#3]
I have create a destination both ways, block and closure via your code. I run the app on a device and connect via "Gorges Midi Keyboard" to the created virtual destination but the block or closure never gets called?

I would very happy to provide some dinner for kitty if you can help here!

**Comment by genedelisa** [comment]
Could you send me your code?

That would help me track it down better.

gene

## 

Dr. Gene De Lisa
gene@rockhoppertech.com
75 Trueman Ave.
Haddonfield, NJ 08033-2529
Skype: gene.de.lisa
http://twitter.com/GeneDeLisaDev
http://rockhoppertech.com/blog/

**Comment by ghost** [comment]
I just downloaded your project as is and ran it.

Checked it had the background flag.

Ran it on my iPad while debugging and attached to  "com.rockhoppertech.VirtualDest" from "Gorges Midi Keybaord" App then hit a couple of notes, 

Both:

``` swift
            status = MIDIDestinationCreateWithBlock(midiClient,
                "com.rockhoppertech.VirtualDest",
                &destEndpointRef,
                readBlock)
```

and 

``` swift
            status = MIDIDestinationCreateWithBlock(midiClient,
                "Virtual Dest",
                &destEndpointRef,
                { (packetList:UnsafePointer<MIDIPacketList>, src:UnsafeMutablePointer<Void>) -> Void in

                    let packets = packetList.memory
                    let packet:MIDIPacket = packets.packet

                    // do the loop here...

                    self.handle(packet)

            })
```

Never responded to the expected Midi Notes from the Midi Keyboard?

Even if you say there seems to be a problem, kitty still gets her dinner(s)!

**Comment by ghost** [comment]
The problem is everything to do with destination endpoints needs to be wrapped in a background block. Works OK on an iPad in iOS 9.x with multitasking implements, but only while both App are visible.

Sorry Kitty doesn't get some extra dinners
